openapi: "3.1.0"
info:
  contact:
    email: "contact@passbolt.com"
  description:
    $ref: "components/descriptions.yml#/main"
  license:
    name: "AGPL-3.0"
    url: "https://www.gnu.org/licenses/agpl-3.0.html"
  termsOfService: "https://www.passbolt.com/terms"
  title: "Passbolt API"
  version: "5.0.0"

servers:
  - url: "https://passbolt.local"
    description: "API Passbolt"

paths:
  /auth/is-authenticated.json:
    $ref: "paths/authIsAuthenticated.yml"
  /auth/jwt/jwks.json:
    $ref: "paths/authJwtJwks.yml"
  /auth/jwt/login.json:
    $ref: "paths/authJwtLogin.yml"
  /auth/jwt/logout.json:
    $ref: "paths/authJwtLogout.yml"
  /auth/jwt/refresh.json:
    $ref: "paths/authJwtRefresh.yml"
  /auth/jwt/rsa.json:
    $ref: "paths/authJwtRsa.yml"
  /auth/login.json:
    $ref: "paths/authLogin.yml"
  /auth/logout.json:
    $ref: "paths/authLogout.yml"
  /auth/verify.json:
    $ref: "paths/authVerify.yml"
  /avatars/view/{avatarId}/{avatarFormat}:
    $ref: "paths/avatarsView.yml"
  /comments/{commentId}.json:
    $ref: "paths/comment.yml"
  /comments/resource/{resourceId}.json:
    $ref: "paths/comments.yml"
  /directorysync/synchronize/dry-run.json:
    $ref: "paths/directorySyncDryRun.yml"
  /directorysync/synchronize.json:
    $ref: "paths/directorySync.yml"
  /favorite/{favoriteId}.json:
    $ref: "paths/favorite.yml"
  /favorite/{foreignModel}/{foreignId}.json:
    $ref: "paths/favoritesForeignModel.yml"
  /folders.json:
    $ref: "paths/folders.yml"
  /folders/{folderId}.json:
    $ref: "paths/folder.yml"
  /gpgkeys.json:
    $ref: "paths/gpgkeys.yml"
  /gpgkeys/{gpgkeyId}.json:
    $ref: "paths/gpgkey.yml"
  /groups.json:
    $ref: "paths/groups.yml"
  /groups/{groupId}.json:
    $ref: "paths/group.yml"
  /groups/{groupId}/dry-run.json:
    $ref: "paths/groupDryRun.yml"
  /healthcheck.json:
    $ref: "paths/healthcheck.yml"
  /healthcheck/status.json:
    $ref: "paths/healthcheckStatus.yml"
  /metadata/keys.json:
    $ref: "paths/metadataKeys.yml"
  /metadata/keys/{metadataKeyId}.json:
    $ref: "paths/metadataKey.yml"
  /metadata/keys/privates.json:
    $ref: "paths/metadataKeysPrivates.yml"
  /metadata/keys/private/{metadataPrivateKeyId}.json:
    $ref: "paths/metadataKeysPrivate.yml"
  /metadata/keys/settings.json:
    $ref: "paths/metadataKeysSettings.yml"
  /metadata/types/settings.json:
    $ref: "paths/metadataTypes.yml"
  /metadata/rotate-key/folders.json:
    $ref: "paths/metadataRotateKeyFolders.yml"
  /metadata/rotate-key/resources.json:
    $ref: "paths/metadataRotateKeyResources.yml"
  /metadata/session-keys.json:
    $ref: "paths/metadataSessionKeys.yml"
  /metadata/session-key/{sessionKeyId}.json:
    $ref: "paths/metadataSessionKeyKeys.yml"
  /metadata/rotate-key/tags.json:
    $ref: "paths/metadataRotateKeyTags.yml"
  /metadata/upgrade/folders.json:
    $ref: "paths/metadataUpgradeFolders.yml"
  /metadata/upgrade/resources.json:
    $ref: "paths/metadataUpgradeResources.yml"
  /metadata/upgrade/tags.json:
    $ref: "paths/metadataUpgradeTags.yml"
  /mfa/verify/{mfaProviderName}.json:
    $ref: "paths/mfaVerify.yml"
  /mfa/verify/error.json:
    $ref: "paths/mfaVerifyError.yml"
  /move/{foreignModel}/{foreignId}.json:
    $ref: "paths/move.yml"
  /permissions/resource/{resourceId}.json:
    $ref: "paths/permissionsResource.yml"
  /resources.json:
    $ref: "paths/resources.yml"
  /resources/{resourceId}.json:
    $ref: "paths/resource.yml"
  /resource-types.json:
    $ref: "paths/resourceTypes.yml"
  /resource-types/{resourceTypeId}.json:
    $ref: "paths/resourceType.yml"
  /roles.json:
    $ref: "paths/roles.yml"
  /secrets/resource/{resourceId}.json:
    $ref: "paths/secretsResource.yml"
  /settings.json:
    $ref: "paths/settings.yml"
  /share/{foreignModel}/{foreignId}.json:
    $ref: "paths/shareForeignModel.yml"
  /share/search-aros.json:
    $ref: "paths/shareSearchAros.yml"
  /share/simulate/{foreignModel}/{foreignId}.json:
    $ref: "paths/shareSimulateForeignModel.yml"
  /tags.json:
    $ref: "paths/tags.yml"
  /tags/{resourceOrTagId}.json:
    $ref: "paths/tag.yml"
  /users.json:
    $ref: "paths/users.yml"
  /users/{userId}.json:
    $ref: "paths/user.yml"
  /users/{userId}/dry-run.json:
    $ref: "paths/userDryRun.yml"

tags:
  - name: "Authentication (GPGAuth)"
    description:
      $ref: "components/descriptions/authGpg.yml#/tag"
  - name: "Authentication (JWT)"
    description:
      $ref: "components/descriptions/authJwt.yml#/tag"
  - name: "Avatars"
    description: "Query avatar images."
  - name: "Comments"
    description: "Manipulate comments for resources."
  - name: "Directory Sync"
    description: "Run directory synchronization."
  - name: "Favorites"
    description:
      $ref: "components/descriptions/favorites.yml#/tag"
  - name: "Folders"
    description: "Organize your passwords and share them in bulk using folders."
  - name: "GPG keys"
    description:
      $ref: "components/descriptions/gpgkeys.yml#/tag"
  - name: "Groups"
    description:
      $ref: "components/descriptions/groups.yml#/tag"
  - name: "Healthcheck"
    description: "Gather data about the Passbolt instance's health."
  - name: "Metadata keys"
    description: "Manipulate metadata keys."
  - name: "Metadata private keys"
    description: "Manipulate private keys for metadata."
  - name: "Metadata types settings"
    description: "Retrieve information about the resource types settings selected by the administrators"
  - name: "Metadata rotate key"
    description: "Gather information about metadata keys that needs to be rotated"
  - name: "Metadata session key"
    description: "Gather information on the saved encrypted session keys cache"
  - name: "Metadata upgrade"
    description: "Upgrading elements to the new v5 metadata format"
  - name: "Move"
    description: "Move a folder or a resource across folders."
  - name: "Multi-Factor Authentication"
    description:
      $ref: "components/descriptions/mfaVerify.yml#/tag"
  - name: "Permissions"
    description: "Query permissions for resources."
  - name: "Resources"
    description:
      $ref: "components/descriptions/resources.yml#/tag"
  - name: "Resource types"
    description:
      $ref: "components/descriptions/resourceTypes.yml#/tag"
  - name: "Roles"
    description: "Different categories of users."
  - name: "Secrets"
    description: "Secrets associated to resources."
  - name: "Settings"
    description: "Retrieve the server settings"
  - name: "Shares"
    description:
      $ref: "components/descriptions/shares.yml#/tag"
  - name: "Tags"
    description: "Get tags and add tags to resources to categorize them."
  - name: "Users"
    description:
      $ref: "components/descriptions/users.yml#/tag"

components:
  securitySchemes:
    $ref: "components/securitySchemes.yml"
