// @ts-check

/**
 * @type {import('@docusaurus/plugin-content-docs/src/sidebars/types').SidebarConfig}
 */
const adminSidebar = [
  {
    type: "category",
    label: "Configuration",
    collapsed: false,
    link: { type: "generated-index", slug: 'admin/configuration' },
    items: [{ type: "autogenerated", dirName: "admin/configuration" }],
  },
  {
    type: "category",
    label: "Configure",
    collapsed: false,
    link: { type: "generated-index", slug: 'admin/configure' },
    items: [{ type: "autogenerated", dirName: "admin/configure" }],
  },
  {
    type: "category",
    label: "Migrate",
    collapsed: false,
    link: { type: "generated-index", slug: 'admin/migrate' },
    items: [{ type: "autogenerated", dirName: "admin/migrate" }],
  },
  {
    type: "category",
    label: "Setup",
    collapsed: false,
    link: { type: "generated-index", slug: 'admin/setup' },
    items: [{ type: "autogenerated", dirName: "admin/setup" }],
  },
  {
    type: "category",
    label: "Update",
    collapsed: false,
    link: { type: "generated-index", slug: 'admin/update' },
    items: [{ type: "autogenerated", dirName: "admin/update" }],
  },
];
module.exports = adminSidebar;
