// @ts-check

/**
 * @type {import('@docusaurus/plugin-content-docs/src/sidebars/types').SidebarConfig}
 */
const adminSidebar = [
  {
    type: "category",
    label: "User Provisioning",
    collapsed: false,
    link: { type: "generated-index", slug: 'admin/user-provisioning' },
    items: [{ type: "autogenerated", dirName: "admin/user-provisioning" }],
  },
];
module.exports = adminSidebar;
