// @ts-nocheck

/**
 * @type {import('@docusaurus/plugin-content-docs/src/sidebars/types').SidebarConfig}
 */
const developmentSidebar = [
  {
    type: 'doc',
    id: 'development/index',
    label: 'Introduction',
  },
  {
    type: 'doc',
    id: 'development/getting-started',
    label: 'Getting started',
  },
  {
    type: 'doc',
    id: 'development/authentication',
    label: 'Authentication',
  },
  {
    type: 'category',
    label: 'Resources',
    collapsed: true,
    link: {type: 'doc', id: 'development/resources/index'},
    items: [{ type: 'autogenerated', dirName: 'development/resources' }],
  },
];
module.exports = developmentSidebar;
