// @ts-nocheck

/**
 * @type {import('@docusaurus/plugin-content-docs/src/sidebars/types').SidebarConfig}
 */
const hostingSidebar = [
  {
    type: 'doc',
    id: 'hosting/index',
    label: 'Introduction',
  },

  // ── Install ──────────────────────────────────────────────
  {
    type: 'category',
    label: 'Install',
    collapsed: true,
    link: { type: 'doc', id: 'hosting/install' },
    items: [
      {
        type: 'doc',
        id: 'hosting/requirements',
        label: 'Requirements',
      },
      {
        type: 'category',
        label: 'CE',
        collapsed: true,
        items: [{ type: 'autogenerated', dirName: 'hosting/install/ce' }],
      },
      {
        type: 'category',
        label: 'Pro',
        collapsed: true,
        items: [{ type: 'autogenerated', dirName: 'hosting/install/pro' }],
      },
      {
        type: 'category',
        label: 'Advanced',
        collapsed: true,
        items: [{ type: 'autogenerated', dirName: 'hosting/install/advanced' }],
      },
    ],
  },

  // ── Configure ────────────────────────────────────────────
  {
    type: 'category',
    label: 'Configure',
    collapsed: true,
    link: { type: 'generated-index', slug: 'hosting/configure' },
    items: [
      {
        type: 'category',
        label: 'Database',
        collapsed: true,
        link: { type: 'doc', id: 'hosting/database/index' },
        items: [
          { type: 'doc', id: 'hosting/database/postgres', label: 'PostgreSQL' },
        ],
      },
      {
        type: 'category',
        label: 'OpenPGP',
        collapsed: true,
        link: { type: 'doc', id: 'hosting/openpgp/index' },
        items: [
          { type: 'doc', id: 'hosting/openpgp/generate-keys' },
          { type: 'doc', id: 'hosting/openpgp/generate-keys-jwt' },
          { type: 'doc', id: 'hosting/openpgp/rotation' },
        ],
      },
      {
        type: 'category',
        label: 'TLS',
        collapsed: true,
        link: { type: 'doc', id: 'hosting/tls/index' },
        items: [
          {
            type: 'doc',
            id: 'hosting/tls/troubleshooting',
          },
        ],
      },
      {
        type: 'category',
        label: 'HTTPS',
        collapsed: true,
        link: { type: 'doc', id: 'hosting/tls/https' },
        items: [
          {
            type: 'category',
            label: 'CE',
            collapsed: true,
            items: [{ type: 'autogenerated', dirName: 'hosting/tls/ce' }],
          },
          {
            type: 'category',
            label: 'Pro',
            collapsed: true,
            items: [{ type: 'autogenerated', dirName: 'hosting/tls/pro' }],
          },
        ],
      },
      {
        type: 'category',
        label: 'Email',
        collapsed: true,
        link: { type: 'doc', id: 'hosting/email/index' },
        items: [
          { type: 'doc', id: 'hosting/email/troubleshooting', label: 'Troubleshooting' },
        ],
      },
      {
        type: 'category',
        label: 'LDAP',
        collapsed: true,
        link: { type: 'generated-index', slug: 'hosting/ldap' },
        items: [{ type: 'autogenerated', dirName: 'hosting/ldap' }],
      },
      {
        type: 'doc',
        id: 'hosting/firewall-rules',
        label: 'Firewall Rules',
      },
      {
        type: 'doc',
        id: 'hosting/ntp',
        label: 'NTP',
      },
      {
        type: 'doc',
        id: 'hosting/session-timeout',
        label: 'Session Timeout',
      },
      {
        type: 'doc',
        id: 'hosting/environment-reference',
        label: 'Environment Reference',
      },
    ],
  },

  // ── Maintain ─────────────────────────────────────────────
  {
    type: 'category',
    label: 'Maintain',
    collapsed: true,
    link: { type: 'generated-index', slug: 'hosting/maintain' },
    items: [
      {
        type: 'category',
        label: 'Update',
        collapsed: true,
        link: { type: 'doc', id: 'hosting/update/index' },
        items: [
          { type: 'doc', id: 'hosting/update/almalinux' },
          { type: 'doc', id: 'hosting/update/aws-ami' },
          { type: 'doc', id: 'hosting/update/debian' },
          { type: 'doc', id: 'hosting/update/digital-ocean' },
          { type: 'doc', id: 'hosting/update/docker' },
          { type: 'doc', id: 'hosting/update/from-source' },
          { type: 'doc', id: 'hosting/update/opensuse' },
          { type: 'doc', id: 'hosting/update/oraclelinux' },
          { type: 'doc', id: 'hosting/update/raspberry' },
          { type: 'doc', id: 'hosting/update/redhat' },
          { type: 'doc', id: 'hosting/update/rockylinux' },
          { type: 'doc', id: 'hosting/update/sles' },
          { type: 'doc', id: 'hosting/update/ubuntu' },
          { type: 'doc', id: 'hosting/update/virtual-appliance' },
        ],
      },
      {
        type: 'category',
        label: 'Backup',
        collapsed: true,
        link: { type: 'doc', id: 'hosting/maintenance/backup/index' },
        items: [
          { type: 'doc', id: 'hosting/maintenance/backup/from-docker' },
          { type: 'doc', id: 'hosting/maintenance/backup/from-packages' },
          { type: 'doc', id: 'hosting/maintenance/backup/from-sources' },
        ],
      },
      {
        type: 'category',
        label: 'Performance',
        collapsed: true,
        link: { type: 'generated-index', slug: 'hosting/performance' },
        items: [{ type: 'autogenerated', dirName: 'hosting/maintenance/performance' }],
      },
      {
        type: 'category',
        label: 'Diagnostics',
        collapsed: true,
        link: { type: 'generated-index', slug: 'hosting/diagnostics' },
        items: [{ type: 'autogenerated', dirName: 'hosting/maintenance/diagnostics' }],
      },
      {
        type: 'doc',
        id: 'hosting/useful-commands',
        label: 'Useful Commands',
      },
    ],
  },

  // ── Migrate ──────────────────────────────────────────────
  {
    type: 'category',
    label: 'Migrate',
    collapsed: true,
    link: { type: 'generated-index', slug: 'hosting/migrate' },
    items: [
      {
        type: 'category',
        label: 'Package',
        collapsed: true,
        link: { type: 'doc', id: 'hosting/migrate/package/index' },
        items: [
          {
            type: 'category',
            label: 'CE',
            collapsed: true,
            items: [{ type: 'autogenerated', dirName: 'hosting/migrate/package/ce' }],
          },
          {
            type: 'category',
            label: 'Pro',
            collapsed: true,
            items: [{ type: 'autogenerated', dirName: 'hosting/migrate/package/pro' }],
          },
        ],
      },
      {
        type: 'category',
        label: 'Server',
        collapsed: true,
        link: { type: 'doc', id: 'hosting/migrate/server/index' },
        items: [
          {
            type: 'category',
            label: 'CE',
            collapsed: true,
            items: [{ type: 'autogenerated', dirName: 'hosting/migrate/server/ce' }],
          },
          {
            type: 'category',
            label: 'Pro',
            collapsed: true,
            items: [{ type: 'autogenerated', dirName: 'hosting/migrate/server/pro' }],
          },
        ],
      },
    ],
  },

  // ── Upgrade to Pro ───────────────────────────────────────
  {
    type: 'category',
    label: 'Upgrade to Pro',
    collapsed: true,
    link: { type: 'doc', id: 'hosting/upgrade/index' },
    items: [
      { type: 'doc', id: 'hosting/upgrade/almalinux' },
      { type: 'doc', id: 'hosting/upgrade/debian' },
      { type: 'doc', id: 'hosting/upgrade/docker' },
      { type: 'doc', id: 'hosting/upgrade/oraclelinux' },
      { type: 'doc', id: 'hosting/upgrade/redhat' },
      { type: 'doc', id: 'hosting/upgrade/rockylinux' },
      { type: 'doc', id: 'hosting/upgrade/ubuntu' },
    ],
  },
];
module.exports = hostingSidebar;
