/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // hostingGuideSidebar: [{
  //   type: 'category',
  //   label: 'Hosting',
  //   collapsed: true,
  //   link: { type: 'generated-index', slug: 'hosting' },
  //   items: [{ type: 'autogenerated', dirName: 'hosting' }],
  // }
  hostingGuideSidebar: [
    {
      type: 'category',
      label: 'Install',
      collapsed: true,
      items: [{ type: 'autogenerated', dirName: 'hosting/install' }],
    },
    {
      type: 'category',
      label: 'Update',
      collapsed: true,
      link: { type: 'generated-index', slug: 'hosting/update' },
      items: [{ type: 'autogenerated', dirName: 'hosting/update' }],
    },
    {
      type: 'category',
      label: 'Backup',
      collapsed: true,
      link: { type: 'generated-index', slug: 'hosting/backup' },
      items: [{ type: 'autogenerated', dirName: 'hosting/backup' }],
    },
  ],
  // adminGuideSidebar: require('./admin.sidebar'),
  // userGuideSidebar: require('./user.sidebar'),
};

module.exports = sidebars;
