// @ts-check

/**
 * @type {import('@docusaurus/plugin-content-docs/src/sidebars/types').SidebarConfig}
 */
const userSidebar = [
  {
    type: 'category',
    label: 'Introduction',
    collapsed: false,
    link: { type: 'doc', id: 'user/introduction' },
    items: [{ type: 'autogenerated', dirName: 'user/introduction' }],
  },
  {
    type: 'category',
    label: 'Quickstart',
    collapsed: false,
    link: { type: 'generated-index', slug: 'user/quickstart' },
    items: [{ type: 'autogenerated', dirName: 'user/quickstart' }],
  },
  {
    type: 'category',
    label: 'Basic Features',
    collapsed: false,
    link: { type: 'generated-index', slug: 'user/basic-features' },
    items: [{ type: 'autogenerated', dirName: 'user/basic-features' }],
  },
  {
    type: 'category',
    label: 'Advanced features',
    collapsed: false,
    link: { type: 'generated-index', slug: 'user/advanced-features' },
    items: [{ type: 'autogenerated', dirName: 'user/advanced-features' }],
  },
  {
    type: 'category',
    label: 'Settings',
    collapsed: false,
    link: { type: 'generated-index', slug: 'user/settings' },
    items: [{ type: 'autogenerated', dirName: 'user/settings' }],
  },
  {
    type: 'category',
    label: 'FAQ',
    collapsed: false,
    link: { type: 'generated-index', slug: 'user/faq' },
    items: [{ type: 'autogenerated', dirName: 'user/faq' }],
  },
];
module.exports = userSidebar;
