.audit:
  stage: audit
  image: node:20
  script:
    - npm ci --include=dev
    # TODO: Revert to `npm audit` once dompurify releases a fix for GHSA-v2wj-7wpq-c8vv
    - npm audit --audit-level=high
    - npm run lint:lockfile
  rules:
    - if: '($CI_PIPELINE_SOURCE == "schedule" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $TARGET_BRANCH )'
      when: on_success

audit-staging:
  extends: .audit
  variables:
    TARGET_BRANCH: develop

audit-production:
  extends: .audit
  variables:
    TARGET_BRANCH: main
