.deploy:
  stage: deploy
  image: gcr.io/google.com/cloudsdktool/google-cloud-cli:latest
  identity: google_cloud
  script: |
    set -e
    rm -rf docs
    mv build docs
    gcloud auth login --cred-file=${GOOGLE_APPLICATION_CREDENTIALS}
    export CLOUDSDK_AUTH_ACCESS_TOKEN=$(gcloud auth print-access-token)
    gcloud storage rsync ./docs "gs://$BUCKET/docs" --recursive --delete-unmatched-destination-objects
    gcloud storage objects update "gs://$BUCKET/**" --cache-control="no-cache"
  rules:
    - if: '$CI_COMMIT_BRANCH == $TARGET_BRANCH'
      when: on_success

deploy-staging:
  extends: .deploy
  variables:
    ENV: 'STAGING'
    BUCKET: 'website-docs-staging-a218d15'
    TARGET_BRANCH: feature/PB-49957

deploy-production:
  extends: .deploy
  variables:
    ENV: 'PRODUCTION'
    BUCKET: 'passbolt-docs-production'
    TARGET_BRANCH: main
